# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './nezzle/ui/ui_opennetworkdialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OpenNetworkDialog(object):
    def setupUi(self, OpenNetworkDialog):
        OpenNetworkDialog.setObjectName("OpenNetworkDialog")
        OpenNetworkDialog.resize(457, 384)
        OpenNetworkDialog.setSizeGripEnabled(False)
        OpenNetworkDialog.setModal(True)
        self.layoutWidget = QtWidgets.QWidget(OpenNetworkDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layoutWidget1 = QtWidgets.QWidget(OpenNetworkDialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layoutWidget2 = QtWidgets.QWidget(OpenNetworkDialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.layoutWidget3 = QtWidgets.QWidget(OpenNetworkDialog)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.layoutWidget4 = QtWidgets.QWidget(OpenNetworkDialog)
        self.layoutWidget4.setGeometry(QtCore.QRect(20, 20, 421, 343))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_13.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.layoutWidget4)
        self.label.setObjectName("labels")
        self.horizontalLayout.addWidget(self.label)
        self.ui_filePathEdit = QtWidgets.QLineEdit(self.layoutWidget4)
        self.ui_filePathEdit.setReadOnly(False)
        self.ui_filePathEdit.setObjectName("ui_filePathEdit")
        self.horizontalLayout.addWidget(self.ui_filePathEdit)
        self.ui_openButton = QtWidgets.QPushButton(self.layoutWidget4)
        self.ui_openButton.setObjectName("ui_openButton")
        self.horizontalLayout.addWidget(self.ui_openButton)
        spacerItem1 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_13.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_13.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.ui_networkNameEdit = QtWidgets.QLineEdit(self.layoutWidget4)
        self.ui_networkNameEdit.setReadOnly(False)
        self.ui_networkNameEdit.setObjectName("ui_networkNameEdit")
        self.horizontalLayout_3.addWidget(self.ui_networkNameEdit)
        spacerItem4 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_13.addLayout(self.horizontalLayout_3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_13.addItem(spacerItem5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget4)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.ui_noLinkTypeCheck = QtWidgets.QCheckBox(self.groupBox)
        self.ui_noLinkTypeCheck.setObjectName("ui_noLinkTypeCheck")
        self.verticalLayout_11.addWidget(self.ui_noLinkTypeCheck)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ui_actSymEdit = QtWidgets.QLineEdit(self.groupBox)
        self.ui_actSymEdit.setDragEnabled(True)
        self.ui_actSymEdit.setObjectName("ui_actSymEdit")
        self.verticalLayout_4.addWidget(self.ui_actSymEdit)
        self.ui_inhSymEdit = QtWidgets.QLineEdit(self.groupBox)
        self.ui_inhSymEdit.setDragEnabled(True)
        self.ui_inhSymEdit.setObjectName("ui_inhSymEdit")
        self.verticalLayout_4.addWidget(self.ui_inhSymEdit)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_11.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5.addWidget(self.groupBox)
        self.ui_sceneSizeGroup = QtWidgets.QGroupBox(self.layoutWidget4)
        self.ui_sceneSizeGroup.setFlat(False)
        self.ui_sceneSizeGroup.setCheckable(False)
        self.ui_sceneSizeGroup.setObjectName("ui_sceneSizeGroup")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.ui_sceneSizeGroup)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.ui_sceneSizeGroup)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_9.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.ui_sceneSizeGroup)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_9.addWidget(self.label_7)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.ui_sceneWidthEdit = QtWidgets.QLineEdit(self.ui_sceneSizeGroup)
        self.ui_sceneWidthEdit.setDragEnabled(True)
        self.ui_sceneWidthEdit.setObjectName("ui_sceneWidthEdit")
        self.verticalLayout_10.addWidget(self.ui_sceneWidthEdit)
        self.ui_sceneHeightEdit = QtWidgets.QLineEdit(self.ui_sceneSizeGroup)
        self.ui_sceneHeightEdit.setDragEnabled(True)
        self.ui_sceneHeightEdit.setObjectName("ui_sceneHeightEdit")
        self.verticalLayout_10.addWidget(self.ui_sceneHeightEdit)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        self.verticalLayout_12.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addWidget(self.ui_sceneSizeGroup)
        self.verticalLayout_13.addLayout(self.horizontalLayout_5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_13.addItem(spacerItem6)
        self.ui_buttonBox = QtWidgets.QDialogButtonBox(self.layoutWidget4)
        self.ui_buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.ui_buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.ui_buttonBox.setObjectName("ui_buttonBox")
        self.verticalLayout_13.addWidget(self.ui_buttonBox)

        self.retranslateUi(OpenNetworkDialog)
        self.ui_buttonBox.accepted.connect(OpenNetworkDialog.accept)
        self.ui_buttonBox.rejected.connect(OpenNetworkDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(OpenNetworkDialog)

    def retranslateUi(self, OpenNetworkDialog):
        _translate = QtCore.QCoreApplication.translate
        OpenNetworkDialog.setWindowTitle(_translate("OpenNetworkDialog", "Dialog"))
        self.label.setText(_translate("OpenNetworkDialog", "File"))
        self.ui_openButton.setText(_translate("OpenNetworkDialog", "Open"))
        self.label_4.setText(_translate("OpenNetworkDialog", "Network Name"))
        self.groupBox.setTitle(_translate("OpenNetworkDialog", "Link Symbol"))
        self.ui_noLinkTypeCheck.setText(_translate("OpenNetworkDialog", "No lins type"))
        self.label_2.setText(_translate("OpenNetworkDialog", "Activation"))
        self.label_3.setText(_translate("OpenNetworkDialog", "Inhibition"))
        self.ui_sceneSizeGroup.setTitle(_translate("OpenNetworkDialog", "Scene Size"))
        self.label_6.setText(_translate("OpenNetworkDialog", "Width"))
        self.label_7.setText(_translate("OpenNetworkDialog", "Height"))

